# Generated by Django 5.2.12 on 2026-03-09 15:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


def migrate_interviews_forward(apps, schema_editor):  # type: ignore[no-untyped-def]
    """Migrate existing Interview records to Transcription + Analysis."""
    Interview = apps.get_model("src", "Interview")
    Transcription = apps.get_model("src", "Transcription")
    Analysis = apps.get_model("src", "Analysis")

    for interview in Interview.objects.all():
        # Determine transcription status
        if interview.status in ("pending", "transcribing"):
            t_status = "pending"
        elif interview.status == "failed" and not interview.transcription:
            t_status = "failed"
        else:
            t_status = "completed"

        transcription = Transcription.objects.create(
            id=interview.id,
            audio_filename=interview.audio_filename,
            audio_file=interview.audio_file,
            transcription=interview.transcription,
            status=t_status,
            error_message=interview.error_message if t_status == "failed" else "",
            created_at=interview.created_at,
            updated_at=interview.updated_at,
        )

        # Create an Analysis if there's analysis data or the interview reached that stage
        has_analysis = interview.analysis and interview.analysis != {}
        was_analyzing = interview.status in ("analyzing", "completed", "failed")

        if has_analysis or (was_analyzing and t_status == "completed"):
            if interview.status == "completed":
                a_status = "completed"
            elif interview.status == "failed" and interview.transcription:
                a_status = "failed"
            else:
                a_status = "pending"

            Analysis.objects.create(
                transcription=transcription,
                cv_id=interview.cv_id,
                prompt=interview.analysis_prompt,
                result=interview.analysis if has_analysis else {},
                status=a_status,
                error_message=interview.error_message if a_status == "failed" else "",
            )


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transcription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('audio_filename', models.CharField(max_length=500)),
                ('audio_file', models.FileField(upload_to='transcriptions/audio/')),
                ('transcription', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('transcribing', 'Transcribing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('prompt', models.TextField(blank=True, default='')),
                ('result', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('analyzing', 'Analyzing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cv', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analyses', to='src.cv')),
                ('transcription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='src.transcription')),
            ],
            options={
                'verbose_name_plural': 'Analyses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RunPython(
            migrate_interviews_forward,
            migrations.RunPython.noop,
        ),
        migrations.DeleteModel(
            name='Interview',
        ),
    ]
