# Generated by Django 5.2.12 on 2026-03-09 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0002_split_interview_into_transcription_and_analysis'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcription',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
